### ISSUE TITLE
Error en 'Compras y Ventas RG 3685'

### ISSUE THREAD

**Issue by jeromarquez** [tryton-ar/citi_afip#20]
Buenas gente, cómo les va?

Estamos haciendo las pruebas previas a una implementación de Tryton en una PyME y luego de varios golpes de cabeza contra la pared hemos logrado dar importantes pasos (sobre los cuales fuimos tomando nota y esperamos pronto poder compartirlos en forma de un bello post que sirva de guía para otres que busquen lo mismo que nosotros).

Escribo para saber si alguien está usando los módulos de la localización Argentina para Tryton 5.0 ya que tenemos los siguientes errores al generar los informes mencionados en el título y queremos saber si es algo general (bug del módulo en la versión 5.0 por ejemplo) o si es que estamos haciendo algo mal.

Paso a detallar:

Error en 'Compras y Ventas RG 3685':

Traceback (most recent call last):
  File "/site-packages/trytond/wsgi.py", line 73, in dispatch_request
    return endpoint(request, **request.view_args)
  File "/site-packages/trytond/protocols/dispatcher.py", line 46, in rpc
    request, database_name, *request.rpc_params)
  File "/site-packages/trytond/wsgi.py", line 44, in auth_required
    return wrapped(*args, **kwargs)
  File "/site-packages/trytond/protocols/wrappers.py", line 122, in wrapper
    return func(request, pool, *args, **kwargs)
  File "/site-packages/trytond/protocols/dispatcher.py", line 176, in _dispatch
    result = rpc.result(meth(*c_args, **c_kwargs))
  File "/site-packages/trytond/wizard/wizard.py", line 287, in execute
    return wizard._execute(state_name)
  File "/site-packages/trytond/wizard/wizard.py", line 318, in _execute
    result = self._execute(transition())
  File "/site-packages/trytond/modules/citi_afip/citi.py", line 155, in transition_exportar_citi
    self.export_citi_alicuota_compras()
  File "/site-packages/trytond/modules/citi_afip/citi.py", line 444, in export_citi_alicuota_compras
    punto_de_venta = punto_de_venta.encode().rjust(5, '0')
TypeError: rjust() argument 2 must be a byte string of length 1, not str

Este error sale solamente cuando intento generar el informe de un período con información cargada (una FC de Proveedor ya pagada con cheques propios), en cambio si lo saco de un período vacío no tira error (y tampoco información, no?).

Error 'Subdiario Compras':

Traceback (most recent call last):
  File "/site-packages/trytond/wsgi.py", line 73, in dispatch_request
    return endpoint(request, **request.view_args)
  File "/site-packages/trytond/protocols/dispatcher.py", line 46, in rpc
    request, database_name, *request.rpc_params)
  File "/site-packages/trytond/wsgi.py", line 44, in auth_required
    return wrapped(*args, **kwargs)
  File "/site-packages/trytond/protocols/wrappers.py", line 122, in wrapper
    return func(request, pool, *args, **kwargs)
  File "/site-packages/trytond/protocols/dispatcher.py", line 176, in _dispatch
    result = rpc.result(meth(*c_args, **c_kwargs))
  File "/site-packages/trytond/report/report.py", line 182, in execute
    oext, content = cls._execute(records, data, action_report)
  File "/site-packages/trytond/report/report.py", line 190, in _execute
    return cls.convert(action, cls.render(action, report_context))
  File "/site-packages/trytond/report/report.py", line 283, in render
    fd, path = cls._prepare_template_file(report)
  File "/site-packages/trytond/report/report.py", line 260, in _prepare_template_file
    raise Exception('Error', 'Missing report file!')
Exception: ('Error', 'Missing report file!')

Este, en cambio, sale siempre, sin importar el período que consulte.

¿Alguna idea de por donde empezar a buscar la solución?

Desde ya agradecemos su atención y les cuento que varios de los problemas que fuimos teniendo los hemos resuelto a través del historial de este foro y del grupo de google de Tryton-Ar.

Saludos!
Jero

**Comment by lukio** [comment]
Creo ticket en proyecto subdiario sobre el error informado por el subdiario compras
