### ISSUE TITLE
The currency quote is not set when create export invoices in other currency than ARS

### ISSUE THREAD

**Issue by lukio** [tryton-ar/citi_afip#6]
When the invoice is in other currency than ARS, we search the currency quote inside the approve xml response. If we do not have the xml reponse, throws an error like this:

```python
Traceback (most recent call last):
  File "/trytond/wsgi.py", line 47, in dispatch_request
    return endpoint(request, **request.view_args)
  File "/trytond/protocols/dispatcher.py", line 41, in rpc
    request, database_name, *request.rpc_params)
  File "/trytond/wsgi.py", line 39, in auth_required
    return wrapped(*args, **kwargs)
  File "/trytond/protocols/wrappers.py", line 106, in wrapper
    return func(request, pool, *args, **kwargs)
  File "/trytond/protocols/dispatcher.py", line 163, in _dispatch
    result = rpc.result(meth(*c_args, **c_kwargs))
  File "/trytond/wizard/wizard.py", line 287, in execute
    return wizard._execute(state_name)
  File "/trytond/wizard/wizard.py", line 318, in _execute
    result = self._execute(transition())
  File "/trytond/modules/citi_afip/citi.py", line 161, in transition_exportar_citi
    self.export_citi_comprobante_ventas()
  File "/trytond/modules/citi_afip/citi.py", line 334, in export_citi_comprobante_ventas
    ctz = Currency.round(invoice.currency, Decimal(ctz))
UnboundLocalError: local variable 'ctz' referenced before assignment
```

If we do not have the xml reponse, we should try to search the currency quote inside the currency.

**Comment by lukio** [comment]
Actualmente tenemos el campo tasa de cambio cargada en el comprobante, asi que debemos utilizar esa información a informar en el citi.

**Comment by lukio** [comment]
REL #23
